import React from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@/native/icons";
import { useTheme } from "@/lib/theme-store";
interface ConfirmDialogProps { visible: boolean; title: string; message: string; icon?: string; iconColor?: string; iconBgColor?: string; confirmText?: string; cancelText?: string; onConfirm: () => void; onCancel?: () => void; destructive?: boolean; }
export function ConfirmDialog({ visible, title, message, icon = "alert-circle-outline", iconColor, iconBgColor, confirmText = "Confirm", cancelText, onConfirm, onCancel, destructive = false }: ConfirmDialogProps) {
 const { colors } = useTheme(); const accent = iconColor || (destructive ? colors.error : colors.primary);
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onCancel || onConfirm}><View style={[styles.backdrop, { backgroundColor: colors.dialogBackdrop }]}><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.iconWrap, { backgroundColor: iconBgColor || colors.primarySoft }]}><Ionicons name={icon} size={23} color={accent} /></View><Text style={[styles.title, { color: colors.foreground }]}>{title}</Text><Text style={[styles.message, { color: colors.muted }]}>{message}</Text><View style={styles.actions}>{cancelText && onCancel ? <Pressable style={[styles.cancelBtn, { backgroundColor: colors.surfaceSubtle }]} onPress={onCancel}><Text style={[styles.cancelText, { color: colors.foreground }]}>{cancelText}</Text></Pressable> : null}<Pressable style={[styles.confirmBtn, { backgroundColor: destructive ? colors.error : colors.primary }, !cancelText && styles.fullWidth]} onPress={onConfirm}><Text style={styles.confirmText}>{confirmText}</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "center", alignItems: "center", padding: 22 }, card: { width: "100%", maxWidth: 370, borderRadius: 24, borderWidth: 1, padding: 24, shadowColor: "#000", shadowOpacity: 0.18, shadowRadius: 24, shadowOffset: { width: 0, height: 8 }, elevation: 8 }, iconWrap: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", marginBottom: 16 }, title: { fontFamily: "Fraunces_700Bold", fontSize: 23, fontWeight: "700", letterSpacing: -0.5 }, message: { fontSize: 13, lineHeight: 20, marginTop: 8 }, actions: { flexDirection: "row", gap: 10, marginTop: 24 }, cancelBtn: { flex: 1, height: 48, borderRadius: 14, alignItems: "center", justifyContent: "center" }, confirmBtn: { flex: 1, height: 48, borderRadius: 14, alignItems: "center", justifyContent: "center" }, fullWidth: { flex: 1 }, cancelText: { fontSize: 13, fontWeight: "700" }, confirmText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" } });
